import type { Project } from './editor';

export const languages = { en: 'English', es: 'Español', fr: 'Français', hi: 'हिन्दी' };
export type Language = keyof typeof languages;
const words = {
  en: { intro:'Build a responsive, accessible app named', system:'Use Material 3 Expressive. Implement the following visual design and navigation as a working frontend app.', theme:'Design system', color:'Primary color', shape:'Corner radius', font:'Typeface', motion:'Motion style', start:'Start on', screen:'Screen', size:'Viewport', background:'Background', components:'Components, from back to front', label:'Label', detail:'Supporting text', position:'Position', dimensions:'Size', variant:'Style', group:'Group', image:'Image source', links:'Interactions and navigation', tap:'Tap', 'swipe-left':'Swipe left', 'swipe-right':'Swipe right', 'swipe-up':'Swipe up', 'swipe-down':'Swipe down', transition:'transition', on:'on', to:'navigate to', end:'Make the controls functional with appropriate hover, focus, pressed, selected and disabled states. Adapt the layout for smaller and larger viewports. Use semantic HTML, keyboard navigation, accessible labels, sufficient contrast and reduced-motion support. Keep this frontend-only, with no backend or API keys. Save user changes in browser storage. Preserve the exact user-authored text above; do not replace it with placeholder copy.', notes:'Additional requirements', hidden:'Hidden', locked:'Locked', none:'none', expressive:'expressive', standard:'standard', slide:'slide', fade:'fade', scale:'scale',phone:'phone',desktop:'desktop' },
  es: { intro:'Crea una aplicación adaptable y accesible llamada', system:'Usa Material 3 Expressive. Implementa el siguiente diseño visual y la navegación como una aplicación frontend funcional.', theme:'Sistema de diseño', color:'Color principal', shape:'Radio de esquina', font:'Tipografía', motion:'Estilo de movimiento', start:'Comienza en', screen:'Pantalla', size:'Ventana', background:'Fondo', components:'Componentes, de atrás hacia delante', label:'Texto', detail:'Texto complementario', position:'Posición', dimensions:'Tamaño', variant:'Estilo', group:'Grupo', image:'Origen de imagen', links:'Interacciones y navegación', tap:'Al tocar', 'swipe-left':'Al deslizar a la izquierda', 'swipe-right':'Al deslizar a la derecha', 'swipe-up':'Al deslizar hacia arriba', 'swipe-down':'Al deslizar hacia abajo', transition:'transición', on:'en', to:'navega a', end:'Haz funcionales los controles con estados de interacción, foco, pulsación, selección y desactivación. Adapta el diseño a ventanas pequeñas y grandes. Usa HTML semántico, navegación por teclado, etiquetas accesibles, contraste suficiente y soporte de movimiento reducido. Mantén la aplicación exclusivamente frontend, sin servidor ni claves de API. Guarda los cambios en el almacenamiento del navegador. Conserva los textos exactos del diseño; no los sustituyas por textos de ejemplo.', notes:'Requisitos adicionales', hidden:'Oculto', locked:'Bloqueado', none:'ninguna', expressive:'expresivo', standard:'estándar', slide:'deslizamiento', fade:'fundido', scale:'escala',phone:'teléfono',desktop:'escritorio' },
  fr: { intro:'Crée une application adaptative et accessible nommée', system:'Utilise Material 3 Expressive. Réalise le design visuel et la navigation suivants dans une application frontend fonctionnelle.', theme:'Système de design', color:'Couleur principale', shape:'Rayon des angles', font:'Police', motion:'Style de mouvement', start:'Commence par', screen:'Écran', size:'Fenêtre', background:'Fond', components:'Composants, de l’arrière vers l’avant', label:'Texte', detail:'Texte complémentaire', position:'Position', dimensions:'Dimensions', variant:'Style', group:'Groupe', image:'Source de l’image', links:'Interactions et navigation', tap:'Appuyer', 'swipe-left':'Balayer vers la gauche', 'swipe-right':'Balayer vers la droite', 'swipe-up':'Balayer vers le haut', 'swipe-down':'Balayer vers le bas', transition:'transition', on:'sur', to:'naviguer vers', end:'Rends les contrôles fonctionnels avec des états de survol, de focus, de pression, de sélection et de désactivation. Adapte la disposition aux fenêtres petites et grandes. Utilise un HTML sémantique, la navigation au clavier, des libellés accessibles, un contraste suffisant et la réduction des animations. Garde une application exclusivement frontend, sans serveur ni clés API. Enregistre les modifications dans le stockage du navigateur. Conserve exactement les textes du design ; ne les remplace pas par des exemples.', notes:'Exigences supplémentaires', hidden:'Masqué', locked:'Verrouillé', none:'aucune', expressive:'expressif', standard:'standard', slide:'glissement', fade:'fondu', scale:'zoom',phone:'téléphone',desktop:'ordinateur' },
  hi: { intro:'इस नाम से एक अनुकूलनीय और सुलभ ऐप बनाएं', system:'Material 3 Expressive का उपयोग करें। निम्न दृश्य डिज़ाइन और नेविगेशन को एक कार्यशील फ्रंटएंड ऐप में लागू करें।', theme:'डिज़ाइन प्रणाली', color:'प्राथमिक रंग', shape:'कोने की त्रिज्या', font:'फ़ॉन्ट', motion:'गति शैली', start:'यहाँ से शुरू करें', screen:'स्क्रीन', size:'व्यूपोर्ट', background:'पृष्ठभूमि', components:'घटक, पीछे से आगे के क्रम में', label:'पाठ', detail:'सहायक पाठ', position:'स्थान', dimensions:'आकार', variant:'शैली', group:'समूह', image:'चित्र स्रोत', links:'इंटरैक्शन और नेविगेशन', tap:'टैप', 'swipe-left':'बाईं ओर स्वाइप', 'swipe-right':'दाईं ओर स्वाइप', 'swipe-up':'ऊपर स्वाइप', 'swipe-down':'नीचे स्वाइप', transition:'ट्रांज़िशन', on:'इस पर', to:'इस स्क्रीन पर जाएं', end:'सभी नियंत्रणों को कार्यशील बनाएं और होवर, फ़ोकस, दबाए गए, चुने गए और निष्क्रिय अवस्थाएं जोड़ें। लेआउट को छोटे और बड़े व्यूपोर्ट के लिए अनुकूल बनाएं। अर्थपूर्ण HTML, कीबोर्ड नेविगेशन, सुलभ लेबल, पर्याप्त कंट्रास्ट और कम गति की प्राथमिकता का समर्थन करें। ऐप को केवल फ्रंटएंड रखें, किसी बैकएंड या API कुंजी के बिना। बदलाव ब्राउज़र स्टोरेज में सहेजें। ऊपर दिए गए उपयोगकर्ता के मूल पाठ को बनाए रखें; उसे नमूना पाठ से न बदलें।', notes:'अतिरिक्त आवश्यकताएं', hidden:'छिपा हुआ', locked:'लॉक किया गया', none:'कोई नहीं', expressive:'अभिव्यंजक', standard:'मानक', slide:'स्लाइड', fade:'फ़ेड', scale:'स्केल',phone:'फ़ोन',desktop:'डेस्कटॉप' },
};
const kindNames: Record<Language, Record<string,string>> = {
 en:{}, es:{button:'botón',chip:'chips',card:'tarjeta',list:'lista',appbar:'barra superior',navbar:'barra de navegación',dialog:'diálogo',textfield:'campo de texto',switch:'interruptor',slider:'deslizador',image:'imagen',divider:'separador',text:'texto',shape:'forma expresiva'},
 fr:{button:'bouton',chip:'puces',card:'carte',list:'liste',appbar:'barre supérieure',navbar:'barre de navigation',dialog:'dialogue',textfield:'champ de texte',switch:'interrupteur',slider:'curseur',image:'image',divider:'séparateur',text:'texte',shape:'forme expressive'},
 hi:{button:'बटन',chip:'चिप',card:'कार्ड',list:'सूची',appbar:'ऐप बार',navbar:'नेविगेशन बार',dialog:'डायलॉग',textfield:'टेक्स्ट फ़ील्ड',switch:'स्विच',slider:'स्लाइडर',image:'चित्र',divider:'विभाजक',text:'पाठ',shape:'अभिव्यंजक आकृति'},
};
export function generatePrompt(p: Project, lang: Language='en', notes=''): string {
 const t=words[lang];
 const lines=[`${t.intro} “${p.name}”.`,t.system,'',`${t.theme}:`,`${t.color}: ${p.theme.color}. ${t.shape}: ${p.theme.shape}px. ${t.font}: ${p.theme.font}. ${t.motion}: ${t[p.theme.motion]}.`,`${t.start}: “${p.screens.find(s=>s.id===p.start)?.name||p.screens[0]?.name||'—'}”.`];
 for(const s of p.screens){
  lines.push('',`${t.screen}: “${s.name}” (${t[s.device]})`,`${t.size}: ${s.w} × ${s.h}px. ${t.background}: ${s.fill}.`,`${t.components}:`);
  s.elements.forEach((e,i)=>{lines.push(`${i+1}. ${kindNames[lang][e.type]||e.type}: ${t.label} “${e.text.replace(/\n/g,' / ')}”. ${t.position}: x=${e.x}, y=${e.y}. ${t.dimensions}: ${e.w} × ${e.h}px.${e.subtext?` ${t.detail}: “${e.subtext}”.`:''}${e.fontSize?` ${t.font}: ${e.fontSize}px.`:''}${e.color?` ${t.color}: ${e.color}.`:''}${e.variant?` ${t.variant}: ${e.variant}.`:''}${e.group?` ${t.group}: ${e.group}.`:''}${e.hidden?` ${t.hidden}.`:''}${e.locked?` ${t.locked}.`:''}${e.src?` ${t.image}: ${e.src.startsWith('data:')?e.text:e.src}.`:''}`);});
 }
 lines.push('',`${t.links}:`);
 for(const l of p.links){const s=p.screens.find(s=>s.id===l.from);const d=p.screens.find(s=>s.id===l.to);const e=s?.elements.find(e=>e.id===l.element);if(s&&d)lines.push(`- ${t[l.trigger]} ${t.on} “${e?.text||s.name}” (${s.name}) → ${t.to} “${d.name}”; ${t.transition}: ${t[l.transition]}.`);}
 lines.push('',t.end);if(notes.trim())lines.push('',`${t.notes}:`,notes.trim());
 return lines.join('\n');
}
